version: "3"
services:
  nginx_app:
    container_name: nginx_app
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 80:80
    restart: always
    links:
      - "node_app"

  node_app:
    container_name: node_app
    build:
      context: ./
      dockerfile: Dockerfile
    command: npm start
    restart: always
    # expose:
    #   - 3001
    ports:
      - 8000:8000
  